name: CI
on:
  workflow_run:
    workflows: ["CI with LH"]
    branches: [main]
    types: 
      - completed

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    permissions:
        deployments: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID_STAGING }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true
          github_deployment: true
          deployment_environment: 'staging'
          github_token: ${{ secrets.GITHUB_TOKEN }}

  lighthouse-check:
    needs: deploy-staging
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        id: lighthouseCheck
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: /tmp/artifacts
          urls: '${{ vars.STAGING_URL}}'
          prCommentEnabled: true
          prCommentSaveOld: true
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Handle Lighthouse Check results
        uses: foo-software/lighthouse-check-status-action@master
        with:
          lighthouseCheckResults: ${{steps.lighthouseCheck.outputs.lighthouseCheckResults }}
          minAccessibilityScore: "95"
          minBestPracticesScore: "95"
          minPerformanceScore: "78"
          minProgressiveWebAppScore: "90"
          minSeoScore: "90"
